/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooELossPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooELossPdf) 

 RooELossPdf::RooELossPdf(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _landauMean,
                        RooAbsReal& _landauVar) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   landauMean("landauMean","landauMean",this,_landauMean),
   landauVar("landauVar","landauVar",this,_landauVar)
 { 
 } 


 RooELossPdf::RooELossPdf(const RooELossPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   landauMean("landauMean",this,other.landauMean),
   landauVar("landauVar",this,other.landauVar)
 { 
 } 



 Double_t RooELossPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return TMath::Landau(-x,landauMean,landauVar) ; 
 } 



